# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Worklog < Formula
  desc "Fast CLI + TUI for logging work highlights and lowlights"
  homepage "https://github.com/jquiaios/worklog"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jquiaios/worklog/releases/download/v1.0.0/worklog_1.0.0_darwin_amd64.tar.gz"
      sha256 "6174388b32da0d438498e1542ce976ba7d4fb167ad814ec5bf8ff895e351ac5b"

      define_method(:install) do
        bin.install "worklog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jquiaios/worklog/releases/download/v1.0.0/worklog_1.0.0_darwin_arm64.tar.gz"
      sha256 "788ea5bd69aa3e3e03c5a7717cedf5ec141fae008ce8ce98444d545e4e1ac706"

      define_method(:install) do
        bin.install "worklog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jquiaios/worklog/releases/download/v1.0.0/worklog_1.0.0_linux_amd64.tar.gz"
      sha256 "8ae1c7601542db7103d9136341378a9162baa09f1692d8ef8042a1865900469d"
      define_method(:install) do
        bin.install "worklog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jquiaios/worklog/releases/download/v1.0.0/worklog_1.0.0_linux_arm64.tar.gz"
      sha256 "364eb6112bd747393a69a16eb204435af0c2cf30319856c39e8f97f9466abff6"
      define_method(:install) do
        bin.install "worklog"
      end
    end
  end

  test do
    system "#{bin}/worklog", "--help"
  end
end
