# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Worklog < Formula
  desc "Fast CLI + TUI for logging work highlights and lowlights"
  homepage "https://github.com/jquiaios/worklog"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jquiaios/worklog/releases/download/v1.1.0/worklog_1.1.0_darwin_amd64.tar.gz"
      sha256 "74563860acf1b99f31a4d47737dd7501147cbb4cdeb470cc4ccdc47917311bd6"

      define_method(:install) do
        bin.install "worklog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jquiaios/worklog/releases/download/v1.1.0/worklog_1.1.0_darwin_arm64.tar.gz"
      sha256 "cb7fdd3af80a147a5201b30b8705ab2ef3b31832a705c3120ec7fdf99e1ff0a2"

      define_method(:install) do
        bin.install "worklog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jquiaios/worklog/releases/download/v1.1.0/worklog_1.1.0_linux_amd64.tar.gz"
      sha256 "b90695e2aa04dec73a38f7f949e5d2602a799c0cf381ba612c28d1a926a79f69"
      define_method(:install) do
        bin.install "worklog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jquiaios/worklog/releases/download/v1.1.0/worklog_1.1.0_linux_arm64.tar.gz"
      sha256 "d0765ed427520b8a6de842d0ee8c4efd6d7dc246690d42b13388786a9c71e047"
      define_method(:install) do
        bin.install "worklog"
      end
    end
  end

  test do
    system "#{bin}/worklog", "--help"
  end
end
